name = "d1-demo-react"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "d1-demo-db"
database_id = "75298027-fc93-43f4-b00d-a0070794ce95"

[env.production]
nodejs_compat = true
[[env.production.d1_databases]]
binding = "DB"
database_name = "d1-demo-db"
database_id = "75298027-fc93-43f4-b00d-a0070794ce95"

[env.preview]
nodejs_compat = true
[[env.preview.d1_databases]]
binding = "DB"
database_name = "d1-demo-db-preview"
database_id = "75298027-fc93-43f4-b00d-a0070794ce95"